<h1>Delete Customer</h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($this->customer->getCompanyName()); ?>'
 </p>
 <?php
 $url = $this->url('nickel/default', array(
     'controller' => 'customer',
     'action'     => 'delete',
     'id'         => $this->id,
 ));
 ?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $this->customer->getCustomerId(); ?>" />
        <input class="btn btn-primary" type="submit" name="del" value="Yes" />
        <input class="btn btn-default" type="submit" name="del" value="No" />
    </div>
</form>
