<div class="row">
    <div class="col-lg-8">     
        <h1>Customers</h1>
    </div>
    <div class="col-lg-4">
        <a style="margin-top: 20px;" class="pull-right btn btn-success btn-sm" href="<?php echo $this->url('nickel/default', array('controller' => 'customer', 'action' => 'add'));?>">
            <span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;New Customer
        </a>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <table class="table">
            <thead>
                <tr>
                    <th>Company Name</th>
                    <th>Telephone No</th>
                    <th>Fax No</td>
                    <th>Email Address</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($this->customers as $customer): ?>
                <tr>
                    <td><a href="<?php echo $this->url('nickel/default', array('controller' => 'customer', 'action' => 'detail', 'id' => $customer->getCustomerId()));?>">
                        <?php echo $customer->getCompanyName();?>
                    </a></td>
                    <td><?php echo $customer->getPhoneNo();?></td>
                    <td><?php echo $customer->getFaxNo();?></td>
                    <td><?php echo $customer->getEmailAddress();?></td>
                    <td style="width: 1%;" nowrap>
                        <a class="btn btn-primary btn-sm" href="<?php echo $this->url('nickel/default', array('controller' => 'customer', 'action' => 'edit', 'id' => $customer->getCustomerId()));?>">
                            <span class="glyphicon glyphicon-pencil"></span>&nbsp;&nbsp;Edit
                        </a>
                        <a class="btn btn-danger btn-sm" href="<?php echo $this->url('nickel/default', array('controller' => 'customer', 'action' => 'delete', 'id' => $customer->getCustomerId()));?>">
                            <span class="glyphicon glyphicon-remove"></span>&nbsp;&nbsp;Delete
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>


