<div class="row">
    <div class="col-lg-8">     
        <h1>Staff List</h1>
    </div>
    <div class="col-lg-4">
        <a style="margin-top: 20px;" class="pull-right btn btn-success btn-sm" href="<?php echo $this->url('nickel/default', array('controller' => 'staff', 'action' => 'add'));?>">
            <span class="glyphicon glyphicon-plus"></span>&nbsp;&nbsp;New Staff Member
        </a>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <table class="table">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>D.O.B.</td>
                    <th>Hire Date</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach($this->staff as $staff): ?>
                <tr>
                    <td><?php echo $staff->getFirstName();?></td>
                    <td><?php echo $staff->getLastName();?></td>
                    <td><?php echo $staff->getBirthDate()->format('d/m/Y');?></td>
                    <td><?php echo $staff->getHireDate()->format('d/m/Y');?></td>
                    <td style="width: 1%;" nowrap>
                        <a class="btn btn-primary btn-sm" href="<?php echo $this->url('nickel/default', array('controller' => 'staff', 'action' => 'edit', 'id' => $staff->getStaffId()));?>">
                            <span class="glyphicon glyphicon-pencil"></span>&nbsp;&nbsp;Edit
                        </a>
                        <a class="btn btn-danger btn-sm" href="<?php echo $this->url('nickel/default', array('controller' => 'staff', 'action' => 'delete', 'id' => $staff->getStaffId()));?>">
                            <span class="glyphicon glyphicon-remove"></span>&nbsp;&nbsp;Delete</a>
                        <a class="btn btn-default btn-sm" href="<?php echo $this->url('nickel/default', array('controller' => 'staff', 'action' => 'avatar', 'id' => $staff->getStaffId()));?>">
                            <span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;Avatar</a>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

