<?php $this->headLink()->appendStylesheet('/css/dashbaord.css'); ?>

<div class="row">
    
    <div class="col-lg-12">
        <div class="jumbotron">
            <h1>Nickel Application</h1>
            <p>Staff and job planning against customers with locations.
               This simple application can serve as a starting point to develop
               a customised application for planning staff and jobs against locations.
            </p>
            <p>
                <a class="btn btn-success btn-lg" href="<?php echo $this->url('gettingstarted'); ?>">
                    Getting Started&nbsp;&nbsp;<span class="glyphicon glyphicon-arrow-right"></span>
                </a>
            </p>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4 col-lg-3"> 
        <div class="dashboard">
            <div class="glyphicon glyphicon-tag"></div>
            <div class="stat"><?php echo $this->jobCount; ?></div>
            <div class="text">Open Jobs</div>
            <div class="dashboard-footnote">
                <a href="<?php echo $this->url('nickel/default', array('controller' => 'job'));?>">more info <span class="glyphicon glyphicon-circle-arrow-right"</span></a>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4 col-lg-3"> 
        <div class="dashboard">
            <div class="glyphicon glyphicon-user"></div>
            <div class="stat"><?php echo $this->staffCount;?></div>
            <div class="text">Staff members</div>
            
            <div class="dashboard-footnote">
                <a href="<?php echo $this->url('nickel/default', array('controller' => 'staff'));?>">more info <span class="glyphicon glyphicon-circle-arrow-right"</span></a>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4 col-lg-3"> 
        <div class="dashboard">
            <div class="glyphicon glyphicon-user"></div>
            <div class="stat"><?php echo $this->customerCount; ?></div>
            <div class="text">Customers</div>
            
            <div class="dashboard-footnote">
                <a href="<?php echo $this->url('nickel/default', array('controller' => 'customer'));?>">more info <span class="glyphicon glyphicon-circle-arrow-right"</span></a>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4 col-lg-3"> 
        <div class="dashboard">
            <div class="glyphicon glyphicon-home"></div>
            <div class="stat"><?php echo $this->locationCount;?></div>
            <div class="text">Locations</div>
            <div class="dashboard-footnote">
                <a href="<?php echo $this->url('nickel/default', array('controller' => 'location'));?>">more info <span class="glyphicon glyphicon-circle-arrow-right"</span></a>
            </div>
        </div>
    </div>
</div>
