<?php
    $this->inlineScript()->appendFile('/js/moment.min.js')
                         ->appendFile('/js/bootstrap-datetimepicker.min.js')
                         ->appendFile('/js/job/edit.js');
?>

<div class="row">
    <div class="col-lg-12">
        <h1>Edit job</h1>
        
        <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('nickel/default', array('controller' => 'job', 'action' => 'edit', 'id' => $this->jobId)))
                 ->prepare();
            echo $this->form()->openTag($form);
        ?>
        
        <div class="form-group">
            <?php echo $this->formRow($form->get('job_id')); ?>
        </div>
        
        <div class="form-group">
            <?php echo $this->formRow($form->get('location_id')); ?>
        </div>
        
        <div class="form-group">
            <?php echo $this->formRow($form->get('staff_id')); ?>
        </div>
        
        <div class="form-group">
            <?php echo $this->formRow($form->get('job_description')); ?>
        </div>
        
        <div class="form-group">
            <?php echo $this->formRow($form->get('notes')); ?>
        </div>
        
        <label>JobType</label>
        <?php $this->formRadio()->setSeparator('</div><div class="radio">');?>
        <div class="radio">
            <?php echo $this->formRadio($form->get('job_type')); ?>
        </div>
        
        <div class="form-group">
            <label>Job Date</label>
            <div class='input-group date' id="job-date-input">
               <?php echo $this->formElement($form->get('job_date')); ?>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
        
        <?php echo $this->formSubmit($form->get('submit')); ?>
        <?php echo $this->form()->closeTag(); ?>
        
    </div>
</div>
