<h1>Add New Staff Member</h1>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('staff/default', array('action' => 'add')))
         ->prepare();
    echo $this->form()->openTag($form);
    echo $this->formHidden($form->get('staff_id'));
?>
<div class="form-group">
    <?php echo $this->formRow($form->get('first_name')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('last_name')); ?>
</div>
<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>
