<?php
    $this->inlineScript()->appendFile('/js/moment.min.js')
                         ->appendFile('/js/bootstrap-datetimepicker.min.js')
                         ->appendFile('/js/staff/edit.js');
?>

<h1>Edit Staff Member</h1>
<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('staff/default', array('action' => 'edit', 'id' => $this->staffId)))
         ->prepare();
    echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php echo $this->formRow($form->get('first_name')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('last_name')); ?>
</div>

<div class="form-group">
    <label>Birth Date</label>
    <div class='input-group date' id="birth-date-input">
        <?php echo $this->formElement($form->get('birth_date')); ?>
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
    </div>
</div>

<div class="form-group">
    <label>Hire Date</label>
    <div class="input-group date" id="hire-date-input">
        <?php echo $this->formElement($form->get('hire_date')); ?>
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
    </div>
</div>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>
