<?php $this->headLink()->appendStylesheet('/css/dashbaord.css'); ?>

<div class="row">
    
    <div class="col-lg-12">
        <div class="jumbotron">
            <h1>Nickel Application</h1>
            <p><?php echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?></p>
            <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Zend Framework 2 on GitHub') ?> &raquo;</a></p>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4 col-lg-3"> 
        <div class="dashboard">
            <div class="glyphicon glyphicon-tag"></div>
            <div class="stat">48</div>
            <div class="text">Open Jobs</div>
            <div class="dashboard-footnote">
                <a href="<?php echo $this->url('staff/default');?>">more info <span class="glyphicon glyphicon-circle-arrow-right"</span></a>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4 col-lg-3"> 
        <div class="dashboard">
            <div class="glyphicon glyphicon-user"></div>
            <div class="stat"><?php echo $this->staffCount;?></div>
            <div class="text">Staff members</div>
            
            <div class="dashboard-footnote">
                <a href="<?php echo $this->url('staff/default');?>">more info <span class="glyphicon glyphicon-circle-arrow-right"</span></a>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4 col-lg-3"> 
        <div class="dashboard">
            <div class="glyphicon glyphicon-user"></div>
            <div class="stat">4</div>
            <div class="text">Customers</div>
            
            <div class="dashboard-footnote">
                <a href="<?php echo $this->url('staff/default');?>">more info <span class="glyphicon glyphicon-circle-arrow-right"</span></a>
            </div>
        </div>
    </div>
    
    <div class="col-sm-6 col-md-4 col-lg-3"> 
        <div class="dashboard">
            <div class="glyphicon glyphicon-home"></div>
            <div class="stat"><?php echo $this->staffCount;?></div>
            <div class="text">25 Locations</div>
            <div class="dashboard-footnote">
                <a href="<?php echo $this->url('staff/default');?>">more info <span class="glyphicon glyphicon-circle-arrow-right"</span></a>
            </div>
        </div>
    </div>
</div>
