<h1>Add New Location</h1>

<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('nickel/default', array('controller' => 'location', 'action' => 'add')))
         ->prepare();
    echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?php echo $this->formRow($form->get('customer_id')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('organisation_name')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($form->get('address_line1')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('address_line2')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('post_town')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('county')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('post_code')); ?>
</div>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>
