<h1>Delete Location</h1>

<p>Are you sure that you want to delete this location? </p>

    <address id="address">
            <strong><?php echo $this->location->getOrganisationName(); ?></strong><br>
            <?php echo $this->location->getFullAddress('<br>'); ?><br>
            <?php echo $this->location->getPostCode(); ?>
    </address>
 </p>
 <?php
 $url = $this->url('nickel/default', array(
     'controller' => 'location',
     'action'     => 'delete',
     'id'         => $this->id,
 ));
 ?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $this->location->getLocationId(); ?>" />
        <input class="btn btn-primary" type="submit" name="del" value="Yes" />
        <input class="btn btn-default" type="submit" name="del" value="No" />
    </div>
</form>
